services:
  models-queen-bee-detector:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV_ID=prod
    ports:
      - 8710:8710
    volumes:
      - ./weights:/app/weights:ro
    restart: unless-stopped
